name: Test

on:
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest tests/ --verbose --rootdir=./tests --cov=api --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v1